package me.zly2006.swiftui.generator

import java.io.File

private const val generatedNotice = "// Generated by swiftui-codegen. Edit the semantic model, not this file.\n"
private fun ValueType.kotlin(): String = when (this) {
    ValueType.Text -> "String"
    ValueType.Number -> "Double"
    ValueType.OptionalNumber -> "Double?"
    ValueType.Boolean -> "Boolean"
    ValueType.Color -> "NativeColor"
    ValueType.Size -> "NativeSize"
    is ValueType.Enumeration -> name
}
private fun ValueType.swift(): String = when (this) {
    ValueType.Text -> "String"
    ValueType.Number -> "Double"
    ValueType.OptionalNumber -> "Double?"
    ValueType.Boolean -> "Bool"
    ValueType.Color -> "NativeColorValue"
    ValueType.Size -> "CGSize"
    is ValueType.Enumeration -> "Int32"
}
private data class AbiField(val name: String, val c: String, val swift: String, val kotlin: String)
private fun Field.abi(): List<AbiField> = when (type) {
    ValueType.Size -> listOf(AbiField("${name}Width", "double", "Double", "$name.width"), AbiField("${name}Height", "double", "Double", "$name.height"))
    ValueType.Color -> listOf(AbiField("${name}Kind", "int32_t", "Int32", "$name.kind")) +
        listOf("red", "green", "blue", "alpha", "opacity").map { AbiField(name + it.replaceFirstChar(Char::uppercase), "double", "Double", "$name.$it") }
    else -> listOf(AbiField(name, when (type) { ValueType.Text -> "const char*"; ValueType.Boolean, is ValueType.Enumeration -> "int32_t"; else -> "double" }, when (type) { ValueType.Text -> "UnsafePointer<CChar>"; ValueType.Boolean, is ValueType.Enumeration -> "Int32"; else -> "Double" }, when (type) { ValueType.OptionalNumber -> "$name ?: Double.NaN"; ValueType.Boolean -> "if ($name) 1 else 0"; is ValueType.Enumeration -> "$name.nativeValue"; else -> name }))
}
private fun Field.swiftArgument() = when (type) {
    ValueType.Text -> "String(cString: $name)"
    ValueType.Boolean -> "$name != 0"
    ValueType.OptionalNumber -> "$name.isNaN ? nil : $name"
    ValueType.Color -> "NativeColorValue(kind: ${name}Kind, red: ${name}Red, green: ${name}Green, blue: ${name}Blue, alpha: ${name}Alpha, opacity: ${name}Opacity)"
    ValueType.Size -> "CGSize(width: ${name}Width, height: ${name}Height)"
    else -> name
}
private fun Binding.config() = "${name}Config" + if (fields.isEmpty()) "" else "(${fields.joinToString { it.name }})"
private fun Callback.cType() = "SUI_${payload?.kotlin()?.replace("?", "") ?: "Action"}Callback"
private fun Callback.swiftPayload() = payload?.swift() ?: "Void"
private fun Callback.kotlinType() = "(" + (payload?.kotlin() ?: "") + ") -> Unit"
private fun Callback.payloadAbi() = payload?.let { Field("value", it).abi() }.orEmpty()
private fun Callback.swiftInvoke() = when (payload) {
    null -> "callback(context)"
    ValueType.Text -> "value.withCString { callback(context, $0) }"
    ValueType.Boolean -> "callback(context, value ? 1 : 0)"
    ValueType.Number -> "callback(context, value)"
    ValueType.Size -> "callback(context, value.width, value.height)"
    else -> error("Callback needs a semantic adapter: $payload")
}

fun generate(destination: File) {
    check(bindings.map { it.abi }.distinct().size == bindings.size)
    bindings.forEach { binding ->
        check(binding.fields.map { it.name }.distinct().size == binding.fields.size)
        check(binding.modifier == null || binding.children == Children.One && binding.callback == null)
    }
    fun output(name: String, body: String) { File(destination, name).apply { parentFile.mkdirs(); writeText(generatedNotice + body) } }
    output("include/NativeUI.h", header())
    output("swift/GeneratedNativeUI.swift", swiftBindings())
    output("common/NativeApi.kt", kotlinApi())
    output("common/NativeComponents.kt", composeComponents())
    output("macos/GeneratedMacosBackend.kt", macosBindings())
    output("api-manifest.tsv", "binding\tC ABI\tchildren\tcallback\tstatus\n" + bindings.joinToString("\n", postfix = "\n") { "${it.name}\tsui_node_${it.abi}_create/update\t${it.children}\t${it.callback?.name ?: "none"}\tgenerated; native compilation and behavior require separate evidence" })
    output("component-whitelist.tsv", "family\tselected adapter\tofficial documentation\n" + componentWhitelist.flatMap { entry -> entry.adapters.sorted().map { "${entry.family}\t$it\t${entry.documentation}" } }.joinToString("\n", postfix = "\n"))
    output("deferred-capabilities.tsv", "family\tcapability\tstatus\n" + componentWhitelist.flatMap { entry -> entry.next.map { "${entry.family}\t$it\tplanned; semantic mapping and behavior verification pending" } }.joinToString("\n", postfix = "\n"))
    println("Generated ${bindings.size} native mappings into ${destination.absolutePath}")
}

private fun header() = buildString {
    append("#pragma once\n#include <stdint.h>\ntypedef void* SUI_Node;\n")
    bindings.mapNotNull { it.callback }.distinctBy { it.cType() }.forEach { callback ->
        append("typedef void (*${callback.cType()})(void* context${callback.payloadAbi().joinToString("") { ", ${it.c} ${it.name}" }});\n")
    }
    for (b in bindings) {
        val fields = b.fields.flatMap { it.abi() }.map { "${it.c} ${it.name}" }
        val callback = b.callback?.let { listOf("${it.cType()} callback", "void* context") }.orEmpty()
        append("SUI_Node sui_node_${b.abi}_create(${(fields + callback).joinToString().ifEmpty { "void" }});\n")
        append("void sui_node_${b.abi}_update(${(listOf("SUI_Node node") + fields).joinToString()});\n")
    }
    append("""
        void sui_node_insert(SUI_Node parent, SUI_Node child, int32_t index);
        void sui_node_remove(SUI_Node parent, int32_t index, int32_t count);
        void sui_node_move(SUI_Node parent, int32_t from, int32_t to, int32_t count);
        void sui_node_clear(SUI_Node parent);
        void sui_node_release(SUI_Node node);
        void* sui_tree_host_create(SUI_Node root);
        void sui_tree_host_release(void* host);
        int32_t sui_tree_live_nodes(void);
        int32_t sui_tree_live_hosts(void);
        int64_t sui_tree_property_updates(void);
        int64_t sui_tree_body_evaluations(void);
        void sui_node_debug_action(SUI_Node node);
        void sui_node_debug_boolean(SUI_Node node, int32_t value);
        void sui_node_debug_string(SUI_Node node, const char* value);
        void sui_node_debug_double(SUI_Node node, double value);
    """.trimIndent() + "\n")
}

private fun kotlinApi() = buildString {
    append("package me.zly2006.swiftui.nativeui\n\n")
    append("data class NativeSize(val width: Double, val height: Double)\n")
    for (enum in enums) append("enum class ${enum.name}(val nativeValue: Int) { ${enum.entries.mapIndexed { i, entry -> "${entry.first}($i)" }.joinToString()} }\n")
    append("""
        @ConsistentCopyVisibility
        data class NativeColor internal constructor(val kind: Int, val red: Double = 0.0, val green: Double = 0.0, val blue: Double = 0.0, val alpha: Double = 1.0, val opacity: Double = 1.0) {
            init { require(listOf(red, green, blue, alpha, opacity).all { it.isFinite() && it in 0.0..1.0 }) }
            fun opacity(value: Double) = copy(opacity = value)
            companion object {
                fun rgba(red: Double, green: Double, blue: Double, alpha: Double = 1.0) = NativeColor(-1, red, green, blue, alpha)
    """.trimIndent() + "\n")
    namedColors.forEachIndexed { i, name -> append("        val $name = NativeColor($i)\n") }
    append("    }\n}\n\n")
    for (b in bindings) {
        if (b.fields.isEmpty()) append("data object ${b.name}Config\n") else {
            append("data class ${b.name}Config(${b.fields.joinToString { "val ${it.name}: ${it.type.kotlin()}" }})\n")
        }
    }
    append("\ninterface NativeUiBackend : NativeTreeBackend {\n")
    for (b in bindings) {
        append("    fun create${b.name}(config: ${b.name}Config${b.callback?.let { ", ${it.name}: ${it.kotlinType()}" }.orEmpty()}): NativeUiElement\n")
        append("    fun update${b.name}(element: NativeUiElement, config: ${b.name}Config)\n")
    }
    append("}\n")
}

private fun composeComponents() = buildString {
    append("package me.zly2006.swiftui.nativeui\n\nimport androidx.compose.runtime.*\n\n")
    for (b in bindings.filter { it.name != "Root" }) {
        val parameters = b.fields.map { "${it.name}: ${it.type.kotlin()}${it.default?.let { d -> " = $d" }.orEmpty()}" } +
            listOfNotNull(b.callback?.let { "${it.name}: ${it.kotlinType()}" }) + listOf("modifier: NativeModifier = NativeModifier") +
            if (b.children == Children.None) emptyList() else listOf("content: @Composable () -> Unit")
        append("@Composable\nfun ${b.name}(${parameters.joinToString()}) {\n")
        append("    val backend = LocalNativeUiBackend.current\n    val config = ${b.config()}\n")
        b.callback?.let { append("    val listener by rememberUpdatedState(${it.name})\n") }
        val callback = b.callback?.let { if (it.payload == null) ", { listener() }" else ", { listener(it) }" }.orEmpty()
        append("    modifier.wrap {\n        ComposeNode<UiNode, NativeUiApplier>(\n            factory = { UiNode(backend, backend.create${b.name}(config$callback)) },\n            update = { set(config) { backend.update${b.name}(element, it) } },\n")
        append("            content = ${if (b.children == Children.None) "{}" else "content"},\n        )\n    }\n}\n\n")
        b.modifier?.let { modifier ->
            val fields = b.fields.joinToString { "${it.name}: ${it.type.kotlin()}${it.default?.let { d -> " = $d" }.orEmpty()}" }
            append("fun NativeModifier.$modifier($fields): NativeModifier = then { content -> ${b.name}(${b.fields.joinToString { "${it.name} = ${it.name}" }}${if (b.fields.isEmpty()) "" else ", "}content = content) }\n\n")
        }
    }
    append("fun NativeModifier.padding(all: Double) = padding(all, all, all, all)\n")
}

private fun swiftBindings() = buildString {
    append("import SwiftUI\nimport Observation\n\n")
    for (enum in enums) {
        append("func nativeUi${enum.name}(_ value: Int32) -> ${enum.swiftType} {\n    switch value {\n")
        enum.entries.forEachIndexed { i, entry -> append("    case $i: return .${entry.second}\n") }
        append("    default: preconditionFailure(\"Invalid ${enum.name}\")\n    }\n}\n")
    }
    append("struct NativeColorValue: Equatable {\n    let kind: Int32\n    let red, green, blue, alpha, opacity: Double\n    var color: SwiftUI.Color {\n        let base: SwiftUI.Color\n        switch kind {\n        case -1: base = Color(.sRGB, red: red, green: green, blue: blue, opacity: alpha)\n")
    namedColors.forEachIndexed { i, name ->
        val swift = name.replaceFirstChar(Char::lowercase)
        append("        case $i: base = .$swift\n")
    }
    append("        default: preconditionFailure(\"Invalid native color\")\n        }\n        return opacity == 1 ? base : base.opacity(opacity)\n    }\n}\n\n")
    for (b in bindings) {
        val config = "${b.name}Configuration"
        val callback = b.callback
        append("struct $config: Equatable {\n${b.fields.joinToString("") { "    let ${it.name}: ${it.type.swift()}\n" }}}\n")
        append("@Observable final class ${b.name}Properties {\n    var configuration: $config\n    init(_ configuration: $config) { self.configuration = configuration }\n}\n")
        append("final class ${b.name}Node: NativeNode {\n    let properties: ${b.name}Properties\n")
        if (callback != null) append("    let relay: NativeRelay<${callback.swiftPayload()}>\n")
        append("    init(_ configuration: $config${callback?.let { ", relay: NativeRelay<${it.swiftPayload()}>" }.orEmpty()}) {\n        properties = ${b.name}Properties(configuration)\n")
        if (callback != null) append("        self.relay = relay\n")
        append("        super.init(childPolicy: ${when (b.children) { Children.None -> 0; Children.One -> 1; Children.Many -> -1 }})\n")
        if (callback != null) append("        deactivate = { relay.active = false }\n")
        append("    }\n    override var nativeView: AnyView { AnyView(${b.name}NativeView(node: self)) }\n}\n")
        val body = enums.fold(b.body) { expression, enum -> expression.replace("native${enum.name}(", "nativeUi${enum.name}(") }
        val configurationRead = if ("c." in body) "        let c = node.properties.configuration\n" else ""
        append("struct ${b.name}NativeView: View {\n    let node: ${b.name}Node\n    @ViewBuilder var body: some View {\n        let _ = recordNativeBodyEvaluation()\n$configurationRead${body.lines().joinToString("\n") { "        $it" }}\n    }\n}\n")
        val fields = b.fields.flatMap { it.abi() }
        val signature = fields.map { "_ ${it.name}: ${it.swift}" } + callback?.let { listOf("_ callback: @escaping @convention(c) (UnsafeMutableRawPointer?${it.payloadAbi().joinToString("") { field -> ", ${field.swift}" }}) -> Void", "_ context: UnsafeMutableRawPointer?") }.orEmpty()
        val configCreate = "$config(${b.fields.joinToString { "${it.name}: ${it.swiftArgument()}" }})"
        append("@_cdecl(\"sui_node_${b.abi}_create\")\npublic func nodeCreate${b.name}(${signature.joinToString()}) -> UnsafeMutableRawPointer {\n    requireNativeMainThread()\n")
        if (callback != null) append("    let relay = NativeRelay<${callback.swiftPayload()}> { value in ${callback.swiftInvoke()} }\n")
        append("    return retainNativeNode(${b.name}Node($configCreate${if (callback != null) ", relay: relay" else ""}))\n}\n")
        append("@_cdecl(\"sui_node_${b.abi}_update\")\npublic func nodeUpdate${b.name}(${(listOf("_ pointer: UnsafeMutableRawPointer") + fields.map { "_ ${it.name}: ${it.swift}" }).joinToString()}) {\n    let node = checkedNativeNode(pointer, ${b.name}Node.self)\n    let configuration = $configCreate\n    if node.properties.configuration != configuration { node.properties.configuration = configuration; recordNativePropertyUpdate() }\n}\n\n")
    }
}

private fun macosBindings() = buildString {
    append("@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)\npackage me.zly2006.swiftui.nativeui\n\nimport me.zly2006.swiftui.capi.*\nimport kotlinx.cinterop.*\n\n")
    for (callback in bindings.mapNotNull { it.callback }.distinctBy { it.cType() }) {
        val arguments = callback.payloadAbi()
        append("private fun ${callback.cType()}(context: COpaquePointer?${arguments.joinToString("") { ", ${it.name}: ${when (it.c) { "const char*" -> "CPointer<ByteVar>?"; "int32_t" -> "Int"; else -> "Double" }}" }}) {\n    checkNativeUiMainThread()\n    val callback = checkNotNull(context).asStableRef<NativeCallback>().get()\n    callback.invoke(${when (callback.payload) { null -> "Unit"; ValueType.Text -> "checkNotNull(value).toKString()"; ValueType.Boolean -> "value != 0"; ValueType.Size -> "NativeSize(valueWidth, valueHeight)"; else -> "value" }})\n}\n")
    }
    append("\nclass MacosNativeUiBackend : BaseMacosNativeUiBackend(), NativeUiBackend {\n")
    for (b in bindings) {
        val callback = b.callback
        val ffiArgs = b.fields.flatMap { it.abi() }.joinToString { it.kotlin.replace(Regex("\\b(${b.fields.joinToString("|") { field -> field.name }})\\b")) { match -> "config.${match.value}" } }
        append("    override fun create${b.name}(config: ${b.name}Config${callback?.let { ", ${it.name}: ${it.kotlinType()}" }.orEmpty()}): NativeUiElement {\n        checkNativeUiMainThread()\n")
        if (callback != null) {
            append("        return ownCallback(\"${b.name}\", NativeCallback { ${callback.name}(${if (callback.payload == null) "" else "it as ${callback.payload.kotlin()}"}) }) { context ->\n            checkNotNull(sui_node_${b.abi}_create($ffiArgs${if (ffiArgs.isEmpty()) "" else ", "}staticCFunction(::${callback.cType()}), context))\n        }\n")
        } else append("        return own(\"${b.name}\") { checkNotNull(sui_node_${b.abi}_create($ffiArgs)) }\n")
        append("    }\n    override fun update${b.name}(element: NativeUiElement, config: ${b.name}Config) {\n        sui_node_${b.abi}_update(checked(element, \"${b.name}\")${if (ffiArgs.isEmpty()) "" else ", "}$ffiArgs)\n    }\n")
    }
    append("}\n")
}
