package me.zly2006.swiftui.generator

import java.io.File

private const val GENERATED_NOTICE = "// Generated by swiftui-codegen. Edit the semantic model, not this file.\n"

private fun ValueType.kotlin(): String =
    when (this) {
        ValueType.Text -> "String"
        ValueType.Number -> "Double"
        ValueType.OptionalNumber -> "Double?"
        ValueType.Boolean -> "Boolean"
        ValueType.Color -> "NativeColor"
        ValueType.Size -> "NativeSize"
        ValueType.Region -> "NativeMapRegion"
        ValueType.Numbers -> "List<Double>"
        ValueType.Colors -> "List<NativeColor>"
        ValueType.Path -> "NativePath"
        is ValueType.Enumeration -> name
    }

private fun ValueType.swift(): String =
    when (this) {
        ValueType.Text -> "String"
        ValueType.Number -> "Double"
        ValueType.OptionalNumber -> "Double?"
        ValueType.Boolean -> "Bool"
        ValueType.Color -> "NativeColorValue"
        ValueType.Size -> "CGSize"
        ValueType.Region -> "NativeMapRegionValue"
        ValueType.Numbers -> "[Double]"
        ValueType.Colors -> "[NativeColorValue]"
        ValueType.Path -> "SwiftUI.Path"
        is ValueType.Enumeration -> "Int32"
    }

// @formatter:off
private data class AbiField(val name: String, val c: String, val swift: String, val kotlin: String)
// @formatter:on

// @formatter:off
private fun Field.abi(): List<AbiField> = when (type) {
    ValueType.Region -> listOf("latitude", "longitude", "latitudeSpan", "longitudeSpan").map { AbiField(name + it.replaceFirstChar(Char::uppercase), "double", "Double", "$name.$it") }
    ValueType.Path -> listOf(AbiField(name, "void*", "UnsafeMutableRawPointer", "${name}Handle"))
    ValueType.Numbers -> listOf(AbiField("${name}Values", "const double*", "UnsafePointer<Double>", "${name}Buffer"), AbiField("${name}Count", "int32_t", "Int32", "$name.size"))
    ValueType.Colors -> listOf(AbiField("${name}Kinds", "const int32_t*", "UnsafePointer<Int32>", "${name}KindsBuffer"), AbiField("${name}Components", "const double*", "UnsafePointer<Double>", "${name}ComponentsBuffer"), AbiField("${name}Count", "int32_t", "Int32", "$name.size"))
    ValueType.Size -> listOf(AbiField("${name}Width", "double", "Double", "$name.width"), AbiField("${name}Height", "double", "Double", "$name.height"))
    ValueType.Color -> listOf(AbiField("${name}Kind", "int32_t", "Int32", "$name.kind")) +
        listOf("red", "green", "blue", "alpha", "opacity").map { AbiField(name + it.replaceFirstChar(Char::uppercase), "double", "Double", "$name.$it") }
    else -> listOf(AbiField(name, when (type) { ValueType.Text -> "const char*"; ValueType.Boolean, is ValueType.Enumeration -> "int32_t"; else -> "double" }, when (type) { ValueType.Text -> "UnsafePointer<CChar>"; ValueType.Boolean, is ValueType.Enumeration -> "Int32"; else -> "Double" }, when (type) { ValueType.OptionalNumber -> "$name ?: Double.NaN"; ValueType.Boolean -> "if ($name) 1 else 0"; is ValueType.Enumeration -> "$name.nativeValue"; else -> name }))
}
// @formatter:on

private fun Field.swiftArgument() =
    when (type) {
        ValueType.Path -> "copiedNativePath($name)"
        ValueType.Numbers -> "Array(UnsafeBufferPointer(start: ${name}Values, count: Int(${name}Count)))"
        ValueType.Colors -> "(0..<Int(${name}Count)).map { index in let offset = index * 5; return NativeColorValue(kind: ${name}Kinds[index], red: ${name}Components[offset], green: ${name}Components[offset + 1], blue: ${name}Components[offset + 2], alpha: ${name}Components[offset + 3], opacity: ${name}Components[offset + 4]) }"
        ValueType.Text -> "String(cString: $name)"
        ValueType.Boolean -> "$name != 0"
        ValueType.OptionalNumber -> "$name.isNaN ? nil : $name"
        ValueType.Color -> "NativeColorValue(kind: ${name}Kind, red: ${name}Red, green: ${name}Green, blue: ${name}Blue, alpha: ${name}Alpha, opacity: ${name}Opacity)"
        ValueType.Size -> "CGSize(width: ${name}Width, height: ${name}Height)"
        ValueType.Region -> "NativeMapRegionValue(latitude: ${name}Latitude, longitude: ${name}Longitude, latitudeSpan: ${name}LatitudeSpan, longitudeSpan: ${name}LongitudeSpan)"
        else -> name
    }

private fun Binding.config() = "${name}Config" + if (fields.isEmpty()) "" else "(${fields.joinToString { it.name }})"

private fun Callback.cType() = "SUI_${payload?.kotlin()?.replace("?", "") ?: "Action"}Callback"

private fun Callback.swiftPayload() = payload?.swift() ?: "Void"

private fun Callback.kotlinType() = "(" + (payload?.kotlin() ?: "") + ") -> Unit"

private fun Callback.payloadAbi() = payload?.let { Field("value", it).abi() }.orEmpty()

private fun Callback.swiftInvoke() =
    when (payload) {
        null -> "callback(context)"
        ValueType.Text -> "value.withCString { callback(context, $0) }"
        ValueType.Boolean -> "callback(context, value ? 1 : 0)"
        ValueType.Number -> "callback(context, value)"
        ValueType.Size -> "callback(context, value.width, value.height)"
        ValueType.Region -> "callback(context, value.latitude, value.longitude, value.latitudeSpan, value.longitudeSpan)"
        ValueType.Color -> "callback(context, value.kind, value.red, value.green, value.blue, value.alpha, value.opacity)"
        else -> error("Callback needs a semantic adapter: $payload")
    }

// @formatter:off
fun generate(destination: File) {
    check(bindings.map { it.abi }.distinct().size == bindings.size)
    bindings.forEach { binding ->
        check(binding.fields.map { it.name }.distinct().size == binding.fields.size)
        check(binding.modifier == null || binding.children == Children.One)
    }
    fun output(name: String, body: String) { File(destination, name).apply { parentFile.mkdirs(); writeText(GENERATED_NOTICE + body) } }
    output("include/NativeUI.h", header())
    output("swift/GeneratedNativeUI.swift", swiftBindings())
    output("common/NativeApi.kt", kotlinApi())
    output("common/NativeComponents.kt", composeComponents())
    output("macos/GeneratedMacosBackend.kt", macosBindings())
    output("api-manifest.tsv", "binding\tC ABI\tchildren\tcallback\tstatus\n" + bindings.joinToString("\n", postfix = "\n") { "${it.name}\tsui_node_${it.abi}_create/update\t${it.children}\t${it.callback?.name ?: "none"}\tgenerated; native compilation and behavior require separate evidence" })
    output("component-whitelist.tsv", "family\tselected adapter\tofficial documentation\n" + componentWhitelist.flatMap { entry -> entry.adapters.sorted().map { "${entry.family}\t$it\t${entry.documentation}" } }.joinToString("\n", postfix = "\n"))
    output("deferred-capabilities.tsv", "family\tcapability\tstatus\n" + componentWhitelist.flatMap { entry -> entry.next.map { "${entry.family}\t$it\tplanned; semantic mapping and behavior verification pending" } }.joinToString("\n", postfix = "\n"))
    println("Generated ${bindings.size} native mappings into ${destination.absolutePath}")
}
// @formatter:on

private fun header() =
    buildString {
        append("#pragma once\n#include <stdint.h>\ntypedef void* SUI_Node;\n")
        append(
            "void* sui_path_create(void);\nint32_t sui_path_live(void);\nint64_t sui_path_constructions(void);\nvoid sui_path_move(void* path, double x, double y);\nvoid sui_path_line(void* path, double x, double y);\nvoid sui_path_curve(void* path, double x, double y, double c1x, double c1y, double c2x, double c2y);\nvoid sui_path_arc(void* path, double x, double y, double radius, double start, double end, int32_t clockwise);\nvoid sui_path_close(void* path);\nvoid sui_path_release(void* path);\n",
        )
        bindings.mapNotNull { it.callback }.distinctBy { it.cType() }.forEach { callback ->
            append(
                "typedef void (*${callback.cType()})(void* context${callback.payloadAbi().joinToString("") { ", ${it.c} ${it.name}" }});\n",
            )
        }
        for (b in bindings) {
            val fields = b.fields.flatMap { it.abi() }.map { "${it.c} ${it.name}" }
            val callback = b.callback?.let { listOf("${it.cType()} callback", "void* context") }.orEmpty()
            append("SUI_Node sui_node_${b.abi}_create(${(fields + callback).joinToString().ifEmpty { "void" }});\n")
            append("void sui_node_${b.abi}_update(${(listOf("SUI_Node node") + fields).joinToString()});\n")
        }
        append(
            """
            void sui_node_insert(SUI_Node parent, SUI_Node child, int32_t index);
            void sui_node_remove(SUI_Node parent, int32_t index, int32_t count);
            void sui_node_move(SUI_Node parent, int32_t from, int32_t to, int32_t count);
            void sui_node_clear(SUI_Node parent);
            void sui_node_release(SUI_Node node);
            void* sui_tree_host_create(SUI_Node root);
            void sui_tree_host_release(void* host);
            int32_t sui_tree_live_nodes(void);
            int32_t sui_tree_live_hosts(void);
            int64_t sui_tree_property_updates(void);
            int64_t sui_tree_body_evaluations(void);
            void sui_node_debug_action(SUI_Node node);
            void sui_node_debug_boolean(SUI_Node node, int32_t value);
            void sui_node_debug_string(SUI_Node node, const char* value);
            void sui_node_debug_double(SUI_Node node, double value);
            void sui_node_debug_color(SUI_Node node, int32_t valueKind, double valueRed, double valueGreen, double valueBlue, double valueAlpha, double valueOpacity);
            void sui_node_debug_size(SUI_Node node, double valueWidth, double valueHeight);
            """.trimIndent() + "\n",
        )
    }

private fun ApiRef.documentation(): String {
    val framework = if (module == "SwiftUICore") "swiftui" else module.lowercase()
    val type = owner.lowercase().replace('.', '/')
    return "https://developer.apple.com/documentation/$framework/$type"
}

private fun Binding.documentation() =
    references.distinct().joinToString("\n") {
        " *\n * [${it.owner}${it.member?.let { member -> ".$member" }.orEmpty()}](${it.documentation()}) in Apple Documentation\n"
    }

private fun Binding.kdoc(
    summary: String,
    property: Boolean = false,
    component: Boolean = false,
    backend: Boolean = false,
    update: Boolean = false,
): String =
    buildString {
        append("/**\n * $summary\n")
        append(documentation())
        if (!backend) fields.forEach { append(" * @${if (property) "property" else "param"} ${it.name} Native `${it.name}` parameter.\n") }
        if (backend) {
            if (update) append(" * @param element Existing element created by this backend's $name factory.\n")
            append(" * @param config Immutable native configuration.\n")
            if (!update) callback?.let { append(" * @param ${it.name} Receives native events; update Kotlin state here.\n") }
        }
        if (component) {
            callback?.let { append(" * @param ${it.name} Callback invoked by the native control; keep controlled state in Kotlin.\n") }
            append(" * @param modifier Native-backed Compose modifier chain, ordered from outermost to innermost.\n")
            if (slots.isNotEmpty()) {
                slots.forEach { append(" * @param $it Composable content for the native $it slot.\n") }
            } else if (children != Children.None) {
                append(" * @param content Child content rendered by the native container.\n")
            }
        }
        append(" */\n")
    }

// @formatter:off
private fun kotlinApi() = buildString {
    append("package me.zly2006.swiftui.nativeui\n\n")
    append("/** Native dimensions in points.\n * @property width Horizontal extent in points.\n * @property height Vertical extent in points.\n * [GeometryProxy.size](https://developer.apple.com/documentation/swiftui/geometryproxy/size) in Apple Documentation\n */\ndata class NativeSize(val width: Double, val height: Double)\n")
    for (enum in enums) {
        val ref = if (enum.nativeMapping) ApiRef("SwiftUI", enum.swiftType.removePrefix("SwiftUI.")) else ApiRef(if (enum.name == "ChartMark") "Charts" else "SwiftUI", if (enum.name == "ChartMark") "Chart" else "PickerStyle")
        append("/** Native options for ${enum.name}.\n * @property nativeValue Integer discriminator used by the typed native bridge.\n * [${ref.owner}](${ref.documentation()}) in Apple Documentation\n */\nenum class ${enum.name}(val nativeValue: Int) {\n")
        enum.entries.forEachIndexed { i, entry -> append("    /** Selects the native `${entry.second}` option. */\n    ${entry.first}($i)${if (i == enum.entries.lastIndex) ";" else ","}\n") }
        append("}\n")
    }
    append("""
        /** A named native color or extended-sRGB color, resolved by SwiftUI.
         * @property kind Internal native color discriminator; use named colors or [rgba].
         * @property red Extended-sRGB red component for custom colors.
         * @property green Extended-sRGB green component for custom colors.
         * @property blue Extended-sRGB blue component for custom colors.
         * @property alpha Base alpha for custom colors, between zero and one.
         * @property opacity Additional opacity multiplier, between zero and one.
         * [Color](https://developer.apple.com/documentation/swiftui/color) in Apple Documentation
         */
        @ConsistentCopyVisibility
        data class NativeColor internal constructor(val kind: Int, val red: Double = 0.0, val green: Double = 0.0, val blue: Double = 0.0, val alpha: Double = 1.0, val opacity: Double = 1.0) {
            init { require(red.isFinite() && green.isFinite() && blue.isFinite()); require(alpha.isFinite() && alpha in 0.0..1.0 && opacity.isFinite() && opacity in 0.0..1.0) }
            /** Returns this color with its opacity multiplier replaced by [value] in the range 0..1. */
            fun opacity(value: Double) = copy(opacity = value)
            /** Native named colors and custom color constructors. */
            companion object {
                /** Creates an extended-sRGB color from finite RGB components and alpha in the range 0..1.
                 * @param red Extended-sRGB red component.
                 * @param green Extended-sRGB green component.
                 * @param blue Extended-sRGB blue component.
                 * @param alpha Base opacity between zero and one.
                 */
                fun rgba(red: Double, green: Double, blue: Double, alpha: Double = 1.0) = NativeColor(-1, red, green, blue, alpha)
    """.trimIndent() + "\n")
    namedColors.forEachIndexed { i, name ->
        val description = if (name == "WindowBackground") "AppKit's adaptive window background color." else "SwiftUI's named $name color, resolved in the current native environment."
        append("        /** $description */\n        val $name = NativeColor($i)\n")
    }
    append("    }\n}\n\n")
    for (b in bindings) {
        append(b.kdoc("Immutable configuration forwarded to the native ${b.name} adapter.", property = true))
        if (b.fields.isEmpty()) append("data object ${b.name}Config\n") else {
            append("data class ${b.name}Config(${b.fields.joinToString { "val ${it.name}: ${it.type.kotlin()}" }})")
            if (b.validation.isNotEmpty()) append(" { init { ${b.validation.joinToString("; ") { "require($it)" }} } }")
            append("\n")
        }
    }
    append("\n/** Creates and updates typed native elements. Detach owned elements before releasing them. */\ninterface NativeUiBackend : NativeTreeBackend {\n")
    for (b in bindings) {
        append(b.kdoc("Creates an unparented ${b.name} element owned by this backend. Release it after detaching it.", backend = true).prependIndent("    "))
        append("    fun create${b.name}(config: ${b.name}Config${b.callback?.let { ", ${it.name}: ${it.kotlinType()}" }.orEmpty()}): NativeUiElement\n")
        append(b.kdoc("Updates an existing ${b.name} element without replacing its identity.", backend = true, update = true).prependIndent("    "))
        append("    fun update${b.name}(element: NativeUiElement, config: ${b.name}Config)\n")
    }
    append("}\n")
}
// @formatter:on

// @formatter:off
private fun composeComponents() = buildString {
    append("package me.zly2006.swiftui.nativeui\n\nimport androidx.compose.runtime.*\nimport androidx.compose.ui.Modifier\n\n")
    for (b in bindings.filter { it.name != "Root" }) {
        val parameters = b.fields.map { "${it.name}: ${it.type.kotlin()}${it.default?.let { d -> " = $d" }.orEmpty()}" } +
            listOfNotNull(b.callback?.let { "${it.name}: ${it.kotlinType()}" }) + listOf("modifier: Modifier = Modifier") +
            if (b.children == Children.None) emptyList() else if (b.slots.isNotEmpty()) b.slots.map { "$it: @Composable () -> Unit" } else listOf("content: @Composable () -> Unit")
        append(b.kdoc("Renders the official native ${b.references.first().owner} capability using Compose state updates.", component = true))
        append("@Composable\n${if (b.publicComponent) "" else "internal "}fun ${b.name}(${parameters.joinToString()}) {\n")
        append("    val backend = LocalNativeUiBackend.current\n    val config = ${b.config()}\n")
        b.callback?.let { append("    val listener by rememberUpdatedState(${it.name})\n") }
        val callback = b.callback?.let { if (it.payload == null) ", { listener() }" else ", { listener(it) }" }.orEmpty()
        append("    modifier.renderNative {\n        ComposeNode<UiNode, NativeUiApplier>(\n            factory = { UiNode(backend, backend.create${b.name}(config$callback)) },\n            update = { set(config) { backend.update${b.name}(element, it) } },\n")
        val childContent = if (b.children == Children.None) "{}" else if (b.slots.isNotEmpty()) "{ ${b.slots.joinToString("; ") { "Group(content = $it)" }} }" else "content"
        append("            content = $childContent,\n        )\n    }\n}\n\n")
        b.modifier?.takeUnless { b.handwrittenModifier }?.let { modifier ->
            val fields = (b.fields.map { "${it.name}: ${it.type.kotlin()}${it.default?.let { d -> " = $d" }.orEmpty()}" } + listOfNotNull(b.callback?.let { "${it.name}: ${it.kotlinType()}" })).joinToString()
            val arguments = (b.fields.map { "${it.name} = config.${it.name}" } + listOfNotNull(b.callback?.let { "${it.name} = ${it.name}" }) + "content = content").joinToString()
            val members = listOf("val config: ${b.name}Config") + listOfNotNull(b.callback?.let { "val ${it.name}: ${it.kotlinType()}" })
            val construct = listOf(b.config()) + listOfNotNull(b.callback?.name)
            if (b.fields.isEmpty() && b.callback == null) {
                append("private data object ${b.name}ModifierElement : NativeViewModifierElement {\n    @Composable override fun Content(content: @Composable () -> Unit) { ${b.name}(content = content) }\n}\n")
                append(b.kdoc("Adds the native $modifier effect to this Compose modifier chain."))
                append("fun Modifier.$modifier($fields): Modifier = then(${b.name}ModifierElement)\n\n")
            } else {
                append("private data class ${b.name}ModifierElement(${members.joinToString()}) : NativeViewModifierElement {\n    @Composable override fun Content(content: @Composable () -> Unit) { ${b.name}($arguments) }\n}\n")
                append(b.kdoc("Adds the native $modifier effect to this Compose modifier chain."))
                append("fun Modifier.$modifier($fields): Modifier = then(${b.name}ModifierElement(${construct.joinToString()}))\n\n")
            }
        }
    }

}
// @formatter:on

// @formatter:off
private fun swiftBindings() = buildString {
    append("import SwiftUI\nimport Observation\n\n")
    bindings
        .asSequence()
        .flatMap { it.references }
        .map { it.module }
        .filter { it !in setOf("SwiftUI", "SwiftUICore") }
        .toSortedSet()
        .toList()
        .forEach { append("import $it\n") }
    for (enum in enums.filter { it.nativeMapping }) {
        append("func nativeUi${enum.name}(_ value: Int32) -> ${enum.swiftType} {\n    switch value {\n")
        enum.entries.forEachIndexed { i, entry -> append("    case $i: return .${entry.second}\n") }
        append("    default: preconditionFailure(\"Invalid ${enum.name}\")\n    }\n}\n")
    }
    append("struct NativeColorValue: Equatable {\n    let kind: Int32\n    let red, green, blue, alpha, opacity: Double\n    var color: SwiftUI.Color {\n        let base: SwiftUI.Color\n        switch kind {\n        case -1: base = Color(.sRGB, red: red, green: green, blue: blue, opacity: alpha)\n")
    namedColors.forEachIndexed { i, name ->
        val swift = name.replaceFirstChar(Char::lowercase)
        append("        case $i: base = ${if (name == "WindowBackground") "Color(nsColor: .windowBackgroundColor)" else ".$swift"}\n")
    }
    append("        default: preconditionFailure(\"Invalid native color\")\n        }\n        return opacity == 1 ? base : base.opacity(opacity)\n    }\n}\n\n")
    for (b in bindings) {
        val config = "${b.name}Configuration"
        val callback = b.callback
        append("struct $config: Equatable {\n${b.fields.joinToString("") { "    let ${it.name}: ${it.type.swift()}\n" }}}\n")
        append("@Observable final class ${b.name}Properties {\n    var configuration: $config\n    init(_ configuration: $config) { self.configuration = configuration }\n}\n")
        append("final class ${b.name}Node: NativeNode {\n    let properties: ${b.name}Properties\n")
        b.storage.forEach { append("    let ${it.name}: ${it.type} = ${it.initializer}\n") }
        if (callback != null) append("    let relay: NativeRelay<${callback.swiftPayload()}>\n")
        append("    init(_ configuration: $config${callback?.let { ", relay: NativeRelay<${it.swiftPayload()}>" }.orEmpty()}) {\n        properties = ${b.name}Properties(configuration)\n")
        if (callback != null) append("        self.relay = relay\n")
        append("        super.init(childPolicy: ${when (b.children) { Children.None -> 0; Children.One -> 1; Children.Many -> -1 }})\n")
        val deactivate = listOfNotNull(if (callback != null) "relay.active = false" else null) + b.storage.mapNotNull { it.dispose }
        if (deactivate.isNotEmpty()) append("        deactivate = { [${(listOfNotNull(if (callback != null) "relay" else null) + b.storage.map { it.name }).joinToString()}] in ${deactivate.joinToString("; ")} }\n")
        append("    }\n    override var nativeView: AnyView { AnyView(${b.name}NativeView(node: self)) }\n}\n")
        val body = enums.fold(b.body) { expression, enum -> expression.replace("native${enum.name}(", "nativeUi${enum.name}(") }
        val configurationRead = if ("c." in body) "        let c = node.properties.configuration\n" else ""
        val availableBody = b.macosMajor?.let { "if #available(macOS $it, *) {\n$body\n} else { preconditionFailure(\"Native component requires macOS $it\") }" } ?: body
        append("struct ${b.name}NativeView: View {\n    let node: ${b.name}Node\n    @ViewBuilder var body: some View {\n        let _ = recordNativeBodyEvaluation()\n$configurationRead${availableBody.lines().joinToString("\n") { "        $it" }}\n    }\n}\n")
        val fields = b.fields.flatMap { it.abi() }
        val signature = fields.map { "_ ${it.name}: ${it.swift}" } + callback?.let { listOf("_ callback: @escaping @convention(c) (UnsafeMutableRawPointer?${it.payloadAbi().joinToString("") { field -> ", ${field.swift}" }}) -> Void", "_ context: UnsafeMutableRawPointer?") }.orEmpty()
        val configCreate = "$config(${b.fields.joinToString { "${it.name}: ${it.swiftArgument()}" }})"
        append("@_cdecl(\"sui_node_${b.abi}_create\")\npublic func nodeCreate${b.name}(${signature.joinToString()}) -> UnsafeMutableRawPointer {\n    requireNativeMainThread()\n")
        if (callback != null) append("    let relay = NativeRelay<${callback.swiftPayload()}> { value in ${callback.swiftInvoke()} }\n")
        append("    return retainNativeNode(${b.name}Node($configCreate${if (callback != null) ", relay: relay" else ""}))\n}\n")
        append("@_cdecl(\"sui_node_${b.abi}_update\")\npublic func nodeUpdate${b.name}(${(listOf("_ pointer: UnsafeMutableRawPointer") + fields.map { "_ ${it.name}: ${it.swift}" }).joinToString()}) {\n    let node = checkedNativeNode(pointer, ${b.name}Node.self)\n    let configuration = $configCreate\n    if node.properties.configuration != configuration { node.properties.configuration = configuration; recordNativePropertyUpdate() }\n}\n\n")
    }
    for (payload in listOf(null, ValueType.Boolean, ValueType.Text, ValueType.Number, ValueType.Color, ValueType.Size)) {
        val suffix = when (payload) { null -> "action"; ValueType.Boolean -> "boolean"; ValueType.Text -> "string"; ValueType.Number -> "double"; ValueType.Color -> "color"; else -> "size" }
        val fields = payload?.let { Field("value", it).abi() }.orEmpty()
        val value = payload?.let { Field("value", it).swiftArgument() } ?: "()"
        append("@_cdecl(\"sui_node_debug_$suffix\")\npublic func nativeDebug_$suffix(_ pointer: UnsafeMutableRawPointer${fields.joinToString("") { ", _ ${it.name}: ${it.swift}" }}) {\n    let raw = checkedNativeNode(pointer, NativeNode.self)\n    switch raw {\n")
        for (binding in bindings.filter { it.callback != null && it.callback.payload == payload }) {
            append("    case let node as ${binding.name}Node: node.relay.fire($value)\n")
        }
        append("    default: preconditionFailure(\"Unsupported native callback payload\")\n    }\n}\n")
    }
}
// @formatter:on

// @formatter:off
private fun macosBindings() = buildString {
    append("@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)\npackage me.zly2006.swiftui.nativeui\n\nimport me.zly2006.swiftui.capi.*\nimport kotlinx.cinterop.*\n\n")
    for (callback in bindings.mapNotNull { it.callback }.distinctBy { it.cType() }) {
        val arguments = callback.payloadAbi()
        append("private fun ${callback.cType()}(context: COpaquePointer?${arguments.joinToString("") { ", ${it.name}: ${when (it.c) { "const char*" -> "CPointer<ByteVar>?"; "int32_t" -> "Int"; else -> "Double" }}" }}) {\n    checkNativeUiMainThread()\n    val callback = checkNotNull(context).asStableRef<NativeCallback>().get()\n    callback.invoke(${when (callback.payload) { null -> "Unit"; ValueType.Text -> "checkNotNull(value).toKString()"; ValueType.Boolean -> "value != 0"; ValueType.Size -> "NativeSize(valueWidth, valueHeight)"; ValueType.Region -> "NativeMapRegion(valueLatitude, valueLongitude, valueLatitudeSpan, valueLongitudeSpan)"; ValueType.Color -> "NativeColor(valueKind, valueRed, valueGreen, valueBlue, valueAlpha, valueOpacity)"; else -> "value" }})\n}\n")
    }
    append("/** SwiftUI backend for macOS. All operations require the Apple main thread.\n * @param pathCacheLimits Bounds for geometry retained by this backend.\n */\n")
    append("\nclass MacosNativeUiBackend(pathCacheLimits: NativePathCacheLimits = NativePathCacheLimits()) : BaseMacosNativeUiBackend(pathCacheLimits), NativeUiBackend {\n")
    for (b in bindings) {
        val callback = b.callback
        val ffiArgs = b.fields.flatMap { it.abi() }.joinToString { it.kotlin.replace(Regex("\\b(${b.fields.joinToString("|") { field -> field.name }})\\b")) { match -> "config.${match.value}" } }
        append(b.kdoc("Creates a native ${b.name} element on the main thread.", backend = true).prependIndent("    "))
        append("    override fun create${b.name}(config: ${b.name}Config${callback?.let { ", ${it.name}: ${it.kotlinType()}" }.orEmpty()}): NativeUiElement {\n        checkNativeUiMainThread()\n")
        b.macosMajor?.let { append("        requireNativeMacosVersion($it)\n") }
        val arrays = b.fields.filter { it.type == ValueType.Numbers || it.type == ValueType.Colors || it.type == ValueType.Path }
        fun buffers() = buildString {
            for (field in arrays) {
                val n = field.name
                if (field.type == ValueType.Path) {
                    // Borrowed by the enclosing backend-owned path scope.
                } else if (field.type == ValueType.Numbers) {
                    append("            val ${n}Buffer = allocArray<DoubleVar>(config.$n.size.coerceAtLeast(1))\n")
                    append("            config.$n.forEachIndexed { i, value -> ${n}Buffer[i] = value }\n")
                } else {
                    append("            val ${n}KindsBuffer = allocArray<IntVar>(config.$n.size.coerceAtLeast(1))\n")
                    append("            val ${n}ComponentsBuffer = allocArray<DoubleVar>((config.$n.size * 5).coerceAtLeast(1))\n")
                    append("            config.$n.forEachIndexed { i, color -> val offset = i * 5; ${n}KindsBuffer[i] = color.kind; ${n}ComponentsBuffer[offset] = color.red; ${n}ComponentsBuffer[offset + 1] = color.green; ${n}ComponentsBuffer[offset + 2] = color.blue; ${n}ComponentsBuffer[offset + 3] = color.alpha; ${n}ComponentsBuffer[offset + 4] = color.opacity }\n")
                }
            }
        }
        val paths = arrays.filter { it.type == ValueType.Path }
        fun pathScope(body: String): String = paths.asReversed().fold(body) { nested, field ->
            "withNativePath(config.${field.name}) { ${field.name}Handle ->\n$nested\n}"
        }
        fun nativeScope(operation: String): String {
            val scoped = if (arrays.any { it.type != ValueType.Path }) "memScoped {\n${buffers()}$operation\n}" else operation
            return pathScope(scoped)
        }
        if (callback != null) {
            check(arrays.isEmpty()) { "Collection callback adapters require explicit ownership support" }
            append("        return ownCallback(\"${b.name}\", NativeCallback { ${callback.name}(${if (callback.payload == null) "" else "it as ${callback.payload.kotlin()}"}) }) { context ->\n            checkNotNull(sui_node_${b.abi}_create($ffiArgs${if (ffiArgs.isEmpty()) "" else ", "}staticCFunction(::${callback.cType()}), context))\n        }\n")
        } else if (arrays.isNotEmpty()) {
            append("        return ${nativeScope("own(\"${b.name}\") { checkNotNull(sui_node_${b.abi}_create($ffiArgs)) }")}\n")
        } else append("        return own(\"${b.name}\") { checkNotNull(sui_node_${b.abi}_create($ffiArgs)) }\n")
        append("    }\n")
        append(b.kdoc("Updates a native ${b.name} element on the main thread.", backend = true, update = true).prependIndent("    "))
        append("    override fun update${b.name}(element: NativeUiElement, config: ${b.name}Config) {\n")
        if (arrays.isNotEmpty()) append("        ${nativeScope("sui_node_${b.abi}_update(checked(element, \"${b.name}\")${if (ffiArgs.isEmpty()) "" else ", "}$ffiArgs)")}\n")
        else append("        sui_node_${b.abi}_update(checked(element, \"${b.name}\")${if (ffiArgs.isEmpty()) "" else ", "}$ffiArgs)\n")
        append("    }\n")
    }
    append("}\n")
}
// @formatter:on
